name: 'padmashree12 testing'
description: 'Updates contributors file'
inputs:
  repo:  # id of input
    description: 'Url of your repository'
    required: true


outputs:
  response:
    description: 'Output from command'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo }}
