name: 'padmashree12 testing'
description: 'Updates contributors file'
outputs:
  response:
    description: 'Output from command'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ github.repository }}
